# Generated by Django 4.1.3 on 2022-11-01 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shortener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_url", models.CharField(max_length=255, unique=True)),
                ("short_url", models.CharField(blank=True, max_length=6, unique=True)),
                ("publishing_date", models.DateField(auto_now_add=True)),
                (
                    "expiration_date",
                    models.DateField(default=datetime.date(2023, 1, 30)),
                ),
            ],
        ),
    ]
