# Generated by Django 4.1.3 on 2022-11-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortener",
            name="short_part",
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="shortener",
            name="short_url",
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
