# Generated by Django 4.1.3 on 2022-11-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_shortener_short_part_alter_shortener_short_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortener",
            name="expiration_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="shortener",
            name="publishing_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="shortener",
            name="short_url",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
